draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: ''
  footer_text: ''
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {
    "&sk GRAVE": ">",
    "&macro 0": "MCRO 0",
    "&macro 1": "MCRO 1",
    "&macro 2": "MCRO 2",
    "&macro 3": "MCRO 3",
    "&macro 4": "MCRO 4",
    "&macro 5": "MCRO 5",
    "&macro 6": "MCRO 6",
    "&macro 7": "MCRO 7",
    "&macro 8": "MCRO 8",
    "&macro 9": "MCRO 9",
  }
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+ {key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_keycode_map:
    'TAB': $$mdi:keyboard-tab$$
    TAB: $$mdi:keyboard-tab$$
    Q: qqq
    W: W
    E: E
    R: R
    T: T
    Y: Y
    U: U
    I: I
    O: O
    P: P
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    LCTRL: $$mdi:apple-keyboard-control$$
    A: A
    S: S
    D: D
    F: F
    G: G
    H: H
    J: J
    K: K
    L: L
    ';': Ö
    "''''": '*'
    LSHFT: $$mdi:apple-keyboard-shift$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    Z: Z
    X: X
    C: C
    V: V
    B: B
    N: N
    M: M
    ',': ','
    '.': .
    '/': '-'
    ESC: ESC
    LALT: $$mdi:apple-keyboard-option$$
    LCMD: $$mdi:apple-keyboard-command$$
    SPACE:
      t: SPACE
      h: EXTRA 1
    RET:
      t: RET
      h: SYMBOL
    NUMBER: NUMBER
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    '+': '+'
    '1': 
      tap: 1
      shifted: '!'
    '2':
      tap: 2
      shifted: '"'
    '3':
      tap: 3
      shifted: '#'
    '4':
      tap: 4
      shifted: €
    '5':
      tap: 5
      shifted: '%'
    '6':
      tap: 6
      shifted: '&'
    '7':
      tap: 7
      shifted: '/'
    '8':
      tap: 8
      shifted: '('
    '9':
      tap: 9
      shifted: ')'
    '0':
      tap: 0
      shifted: '='
    '<': '<'
    '>': '>'
    '-':
      tap: '-'
      shifted: '__'
    '=':
      tap: "´"
      shifted: "`"
    '+': 
      tap: '+'
      shifted: '?'
    '[': Å
    ']':
      tap: '¨'
      shifted: '^'
    '{': '{'
    '}': '}'
    '|': '|'
    ',': ','
    '.': .
    ':': ':'
    '`': '<'
    '~': '~'
    '!': '!'
    '@': '@'
    '#': '#'
    $: $
    '%': '%'
    '^': '^'
    '&': '&'
    '*': '*'
    '(': '('
    ')': ')'
    '_': '_'
    '?': '?'
    '"': 'Ä'
    '{t: ▽, type: trans}': {t: ▽, type: trans}
    '{type: held}': {type: held}
    MPLY: $$mdi:play-pause$$
    MPRV: $$mdi:skip-previous$$
    MNXT: $$mdi:skip-next$$
    MUTE: $$mdi:volume-off$$
    VOLU: $$mdi:volume-high$$
    VOLD: $$mdi:volume-low$$

